LibroLink/urls.py
from django.urls import path
from LibroLink import views
from .views import reviews, ReviewListView
from .views import add_book


app_name = 'LibroLink'

urlpatterns = [
    path('', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),

    path('reviews/', views.reviews, name='reviews'),
    path('reviews/list/', ReviewListView.as_view(), name='review-list'), 
    path('reviews/delete/<int:review_id>/', views.delete_review, name='delete-review'),
    path('reviews/edit/<int:pk>/', views.ReviewUpdateView.as_view(), name='edit-review'),

    path('restricted/', views.restricted, name='restricted'),

    path('profile/', views.profile, name='profile'),
    path('profile/<str:username>/', views.public_profile, name='user_profile'),

    path('search/', views.book_search, name='book_search'),
    path('help_support/', views.help_support, name='help_support'),
    path('privacy/', views.privacy, name='privacy'),

    path('books/', views.books, name='books'),
    path('books/<int:book_id>/', views.book_detail, name='book_detail'),
    path('featured/', views.featured, name='featured'),

    path('friends/', views.friends_list, name='friends_list'),
    path('add_friend/', views.add_friend, name='add_friend'),
  
    path('friend_requests/', views.friend_requests, name='friend_requests'),
    path('user_not_found/<str:username>/', views.user_not_found, name='user_not_found'),
    path('accept_request/<int:request_id>/', views.accept_request, name='accept_request'),
    path('reject_request/<int:request_id>/', views.reject_request, name='reject_request'),

    path('profile/<str:username>/', views.public_profile, name='user_profile'),
    path('add_book/', views.add_book, name='add_book'),
    path('thank_you/', views.thank_you, name='thank_you'),
    
    path('library/', views.books, name='books'),

]

WAD2_6B_2024/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from LibroLink import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('LibroLink/', include('LibroLink.urls')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

LibroLink/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.translation import gettext_lazy as _
from django.template.defaultfilters import slugify


# Create your models here.

class Category(models.Model):

    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

class UserProfile(models.Model): 
    user = models.OneToOneField(User, on_delete=models.CASCADE) 
    picture = models.ImageField(upload_to='profile_images',blank=True) 
    
    def __str__(self): 
        return self.user.username
    

class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='reviews')
    book_name = models.CharField(max_length=255)
    book_author = models.CharField(max_length=255)
    review_text = models.TextField()
    rating = models.DecimalField(max_digits=2, decimal_places=1, validators=[MinValueValidator(0), MaxValueValidator(5)])
    book_image = models.ImageField(upload_to='book_images', blank=True, null=True)

    def __str__(self):
        return f"{self.book_name} by {self.book_author} - {self.user.username}"

    class Meta:
        verbose_name = _("Review")
        verbose_name_plural = _("Reviews")
        ordering = ['-rating'] 
        

class Page(models.Model):
    uniqueID = models.BigIntegerField(default = 0, unique = True)
    name = models.CharField(max_length = 128)
    admin = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    
class Contributors(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

class Followers(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
class Friends(models.Model):
    userA = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friend_user_a")
    userB = models.ForeignKey(User, on_delete=models.CASCADE, related_name="friend_user_b")
    date_established = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ('userA', 'userB')
        
    def __str__(self):
        return self.userA.username + ", " + self.userB.username
    
class FriendRequest(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sent_requests')
    recipient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='received_requests')
    STATUS_CHOICES = (
        ('pending', 'Pending'), 
        ('accepted', 'Accepted'), 
        ('rejected', 'Rejected'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.sender} to {self.recipient}: {self.status}"
    
class Message(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="message_sender")
    receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name="message_receiver")
    timeSent = models.DateTimeField()
    content = models.CharField(max_length = 2000)

    def __str__(self):
        return self.content
    
class BlogPost(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)
    timePosted = models.DateTimeField()
    content = models.CharField(max_length = 4000)

    def __str__(self):
        return self.content
    
class BookCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(BookCategory, self).save(*args, **kwargs)

    def __str__(self):
        return self.name

class Book(models.Model):
    isbn = models.CharField(max_length = 13, unique = True)
    title = models.CharField(max_length = 200)
    author = models.CharField(max_length = 200)
    publisher = models.CharField(max_length = 200)
    category = models.ForeignKey(BookCategory, related_name='books', on_delete=models.CASCADE, null=True, blank=True)
    image = models.ImageField(upload_to='book_covers/', blank=True, null=True)


    def __str__(self):
        return self.title
    
class Featured(models.Model):
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    page = models.ForeignKey(Page, on_delete=models.CASCADE)

    def __str__(self):
        return self.page.name + ": " + self.book.title
    
class Reading(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username + ": " + self.book.title
    
class Read(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    dateFinished = models.DateTimeField()

    def __str__(self):
        return self.self.user.username + ": " + self.book.title
    

LibroLink/forms.py
from django import forms
from django.contrib.auth.models import User 
from LibroLink.models import UserProfile, Review
from LibroLink.models import Book, Reading, Read
from LibroLink.models import BookCategory



class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)

class AddFriendForm(forms.Form):
    username = forms.CharField(max_length=150, label='Friend Username')
        
class ReviewForm(forms.ModelForm):
    
    class Meta:
        model = Review
        fields = ('book_name', 'book_author', 'review_text', 'rating', 'book_image')
        widgets = {
            'rating': forms.NumberInput(attrs={
                'step': 0.5,
                'min': 0,    
                'max': 5,    
            }),
        }
        
class BookSubmissionForm(forms.ModelForm):
    READING_STATUS_CHOICES = [
        ('reading', 'Reading'),
        ('read', 'Read'),
    ]
    status = forms.ChoiceField(choices=READING_STATUS_CHOICES, label="Reading Status")

    class Meta:
        model = Book
        fields = ('isbn', 'title', 'author', 'publisher', 'image', 'category')

templates/LibroLink/add_book.html
{% extends 'LibroLink/base.html' %}

{% load staticfiles %}

{% block title_block %}
Add a Book
{% endblock %}

{% block body_block %}
<div class="container">
  <h1 class="display-4 text-center">Add the Book You're Reading!</h1>
  <div class="row justify-content-center">
    <div class="col-md-8">
      <div class="content_box">
        <form id="book_form" method="post" action="{% url 'LibroLink:add_book' %}" enctype="multipart/form-data" class="form-horizontal">
            {% csrf_token %}
            
            <div class="form-group">
              <label for="id_isbn" class="control-label col-sm-2">ISBN:</label>
              <div class="col-sm-10">
                {{ form.isbn }}
                {{ form.isbn.errors }}
              </div>
            </div>

            <div class="form-group">
              <label for="id_title" class="control-label col-sm-2">Book Name:</label>
              <div class="col-sm-10">
                {{ form.title }}
                {{ form.title.errors }}
              </div>
            </div>

            <div class="form-group">
              <label for="id_author" class="control-label col-sm-2">Book Author:</label>
              <div class="col-sm-10">
                {{ form.author }}
                {{ form.author.errors }}
              </div>
            </div>

            <div class="form-group">
              <label for="id_publisher" class="control-label col-sm-2">Publisher:</label>
              <div class="col-sm-10">
                {{ form.publisher }}
                {{ form.publisher.errors }}
              </div>
            </div>

            <div class="form-group">
              <label for="id_status" class="control-label col-sm-2">Reading Status:</label>
              <div class="col-sm-10">
                {{ form.status }}
                {{ form.status.errors }}
              </div>
            </div>

            <div class="form-group">
              <div class="col-sm-offset-2 col-sm-10">
                <button type="submit" class="btn btn-primary">Add Book</button>
              </div>
            </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/LibroLink/add_friend.html
{% extends 'LibroLink/base.html' %}
{% load static %}

{% block title_block %}
    Add Friend
{% endblock %}
{% block body_block %}
    <h1>Add Friend</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Send Request</button>
    </form>
{% endblock %}

templates/LibroLink/book_detail.html
{% extends 'LibroLink/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {{ book.title }}
{% endblock %}

{% block body_block %}
<main class="container">
    <div class="book-detail">
        <h1>{{ book.title }}</h1>
        <p><strong>ISBN:</strong> {{ book.isbn }}</p>
        <p><strong>Author:</strong> {{ book.author }}</p>
        <p><strong>Publisher:</strong> {{ book.publisher }}</p>
    </div>
</main>
{% endblock %}

templates/LibroLink/books.html
{% extends 'LibroLink/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Books
{% endblock %}

{% block body_block %}
<main class="container">
    <h1>Explore Books by Category</h1>
    {% for category in categories %}
    <div class="category">
        <h2>{{ category.name }}</h2>
        <div class="grid">
            {% for book in category.books.all %}
            <div class="book">
                
                <h3><a href="{% url 'books_detail' book.id %}">{{ book.title }}</a></h3>
                <p>Author: {{ book.author }}</p>
                <p>Publisher: {{ book.publisher }}</p>
            </div>
            {% endfor %}
        </div>
    </div>
    {% endfor %}
</main>
{% endblock %}

templates/LibroLink/category.html
{% extends 'LibroLink/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}

{% block body_block %}
    {% if category %}
    <h1>{{ category.name }}</h1>
    {% if books %}
    <ul>
        {% for book in books %}
        <li><a href="{{ book.url }}">{{ book.title }}</a></li>
        {% endfor %}
    </ul>
    {% else %}
    <strong>No books currently in category.</strong>
    {% endif %}

{% endblock %}

templates/LibroLink/error_page.html
{% extends 'LibroLink/base.html' %}
{% load staticfiles %}

{% block title_block %}
Error
{% endblock %}

{% block body_block %}
<main class="container">
    <h1>Error</h1>
    <p>{{ error_message }}</p>
    <a href="{% url 'LibroLink:index' %}">Return to home page</a>
</main>
{% endblock %}

templates/LibroLink/friends_list.html
{% extends 'LibroLink/base.html' %}
{% load static %}

{% block title_block %}
    Friends List
{% endblock %}
<!-- Does not work... -->
{% block body_block %}
    <h1>Friends List</h1>
    <ul>
        {% for friend in friends %}
            <li>{{ friend.username }}</li>
        {% endfor %}
    </ul>

    <h2>Add Friend</h2>
    <form action="{% url 'add_friend' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add Friend</button>
    </form>
{% endblock %}

templates/LibroLink/index.html
{% extends 'LibroLink/base.html' %}
{% load static %}

{% block title_block %}
    Index
{% endblock %}
{% block body_block %}
<main class="container" style="background-color: #f5f5dc;">
    <div class="grid">
        <section>
            <h1>Welcome to LibroLink Reading Platform</h1>
            <p>Please start reading and share with your friends!</p>
            <form action="{% url 'LibroLink:book_search' %}" method="get" class="search-bar">
                <input type="text" id="searchQuery" name="searchQuery" placeholder="Search for books..." aria-label="Search books" required>
                <button type="submit">Search</button>
            </form>
            <figure>
                <img src="{% static 'images/index.png' %}" alt="Picture of Books" style="width: 100%; max-width: 400px; height: auto;">
                <figcaption><a href="{% url 'LibroLink:featured' %}" target="_blank">Discover the Best Books!</a></figcaption>
            </figure>
        </section>
    </div>
</main>
{% endblock %}

templates/LibroLink/library.html
{% extends 'LibroLink/base.html' %}
{% load static %}

{% block title_block %}
Library
{% endblock %}

{% block body_block %}
<main class="container">
    <h1>Library</h1>
    <div class="book-list">
        {% for book in books %}
            <div class="book-item">
                <h3>{{ book.title }}</h3>
                <p>Author: {{ book.author }}</p>
                <p>Publisher: {{ book.publisher }}</p>
            </div>
        {% empty %}
            <p>No books found.</p>
        {% endfor %}
    </div>
</main>
{% endblock %}

templates/LibroLink/privacy.html
{% extends 'LibroLink/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Privacy Policy
{% endblock %}

{% block body_block %}
<main class="container" style="padding: 20px; background-color: #f5f5dc;">
    <h1>Privacy Policy</h1>
    <div>Update Date: <strong>2024/3/17</strong></div>
    <div>Effective Date: <strong>2024/3/17</strong></div>
    
    <h2>Introduction</h2>
    <p>
        <i>LibroLink</i> is a product provided by <i>Aaron Mclntyre, Aiden Lindsay, Jing Zhang, Lucas Kennington, Maxine Armstrong, Nile Cameron</i> (hereinafter referred to as "we"). When you use our services, we may collect and use your related information. Through this Privacy Policy, we want to explain how we collect, use, store, and share this information when you use our services, as well as the access, update, control, and protection we offer you regarding this information. This Privacy Policy is closely related to the <i>LibroLink</i> services you use, and we hope you carefully read it and make the choices you deem appropriate according to the guidance of this Privacy Policy. We try to express the related technical terms involved in this Privacy Policy in a concise manner and provide links for further explanation to facilitate your understanding.
    </p>
    <p><strong>By using or continuing to use our services, you agree to our collection, use, storage, and sharing of your related information in accordance with this Privacy Policy.</strong></p>
    <p>If you have any questions about this Privacy Policy or related matters, please contact us at <strong>2741773z@student.gla.ac.uk</strong>.</p>

    <h2>1. Information We Collect</h2>
    <p>When providing services, we or our third-party partners may collect, store, and use the following information related to you. If you do not provide relevant information, you may not be able to register as our user or enjoy some of our services, or you may not achieve the intended effects of certain services.</p>
    <ul>
        <li><strong>Personal Information:</strong> The relevant personal information you provide when registering an account or using our services, such as your phone number and email address.</li>
        <li><strong>Log Information:</strong> Refers to the information that the system may collect through cookies, identifiers, and related technologies when you use our services, including your <strong>device information</strong>, <strong>browsing information</strong>, and <strong>click information</strong>, which will be stored as log information. This helps provide you with a personalized user experience and ensures the security of the services. You can refuse or manage the use of cookies, identifiers, or related technologies through your browser settings.</li>
    </ul>

    <h2>2. Storage of Information</h2>
    <strong>2.1 How and Duration of Information Storage</strong>
    <ul>
        <li>We will store your information securely, including local storage (e.g., using APP for data caching), databases, and server logs.</li>
        <li>In general, we will only store your personal information for the duration necessary to achieve the service purposes or as required by laws and regulations.</li>
    </ul>
    <strong>2.2 Storage Location of Information</strong>
    <ul>
        <li>According to legal and regulatory requirements, we will store the personal information of users collected domestically within China.</li>
        <li>Currently, we do not transfer or store your personal information across borders. If it becomes necessary to do so in the future, we will inform you of the purpose of the information export, the recipient, security guarantees, and security risks, and obtain your consent.</li>
    </ul>
    <strong>2.3 Notification in Case of Service Discontinuation</strong>
    <ul>
        <li>If our product or service is discontinued, we will notify you through push notifications, announcements, etc., and delete your personal information or anonymize it within a reasonable period, except as otherwise provided by laws and regulations.</li>
    </ul>

    <h2>3. Information Security</h2>
    <p>
        We use various security technologies and procedures to prevent the loss, improper use, unauthorized viewing, or disclosure of information. For example, in some services, we will use encryption technology (such as SSL) to protect the personal information you provide. However, please understand that due to technical limitations and various malicious methods, it is impossible to always guarantee 100% security of information in the internet industry. You need to be aware that the systems and communication networks you use to access our services may have problems due to factors beyond our control.
    </p>

    <h2>4. How We Use Information</h2>
    <p>We may use the information collected in the course of providing services to you for the following purposes:</p>
    <ul>
        <li>To provide services to you;</li>
        <li>For identity verification, customer service, security prevention, fraud monitoring, archiving, and backup purposes when we provide services, to ensure the safety of the products and services we offer you;</li>
        <li>To help us design new services and improve our existing services;</li>
        <li>To better understand how you access and use our services, so we can respond to your individual needs in a targeted manner, such as language settings, location settings, personalized help services and instructions, or responses to you and other users in other aspects;</li>
        <li>To provide you with more relevant advertisements in place of general ad placements;</li>
        <li>To assess and improve the effectiveness of advertisements and other promotional and promotional activities in our services;</li>
        <li>For software certification or management software upgrades;</li>
        <li>To let you participate in surveys about our products and services.</li>
    </ul>

    <h2>5. Information Sharing</h2>
    <p>
        Currently, we do not actively share or transfer your personal information to third parties. If there is a need to share or transfer your personal information to third parties, we will directly or ensure that third parties obtain your explicit consent for the aforementioned actions.
    </p>
    <p>
        For the purposes of placing advertisements, evaluating, and optimizing the effectiveness of ad placements, etc., we need to share some of your data with advertisers and their agents and other third-party partners, requiring them to strictly comply with our measures and requirements for data privacy protection, including but not limited to processing in accordance with data protection agreements, commitments, and related data processing policies, to avoid identifying individual identities and ensure privacy security.
    </p>
    <p>
        We will not share information that can identify you personally (such as your name or email address) with partners, unless you explicitly authorize it.
    </p>
    <p>
        We will not publicly disclose the personal information collected, except when required to do so by law. If public disclosure is necessary, we will inform you of the purpose of the disclosure, the type of information disclosed, and the sensitive information involved, and obtain your explicit consent.
    </p>
    <p>
        As our business continues to develop, we may undergo mergers, acquisitions, asset transfers, and other transactions. We will inform you of relevant situations and continue to protect your personal information or require new controllers to continue protecting your personal information in accordance with laws, regulations, and standards not lower than those required by this Privacy Policy.
    </p>
    <p>
        Additionally, under the following circumstances, we may share, transfer, and publicly disclose personal information without prior authorization from you, in accordance with relevant laws, regulations, and national standards:
    </p>
    <ul>
        <li>Directly related to national security and national defense security;</li>
        <li>Directly related to public safety, public health, and major public interests;</li>
        <li>Directly related to criminal investigations, prosecutions, trials, and judgment enforcement;</li>
        <li>For the purpose of protecting the significant legal rights and interests of personal information subjects or other individuals, but it is difficult to obtain consent from the person;</li>
        <li>Personal information subjects disclose their personal information to the public on their own;</li>
        <li>Collecting personal information from legally publicly disclosed information, such as legal news reports, government information disclosure, and other channels.</li>
    </ul>

    <h2>6. Your Rights</h2>
    <p>
        During your use of our services, we may, depending on the specific situation of the product, provide you with corresponding operation settings so that you can inquire, delete, correct, or withdraw your relevant personal information. You can refer to the specific instructions for operations. In addition, we have set up a complaint reporting channel, and your opinions will be promptly processed. If you cannot exercise your rights to personal information through the above methods, you can make your request through the contact information provided in this Privacy Policy, and we will respond in accordance with the provisions of laws and regulations.
    </p>
    <p>When you decide to stop using our products or services, you can apply for account cancellation. After the account is canceled, except as otherwise provided by laws and regulations, we will delete or anonymize your personal information.</p>

    <h2>7. Changes</h2>
    <p>
        We may revise the terms of this Privacy Policy in due course. When changes occur, we will prompt you with the updated version of the Privacy Policy and explain the effective date. Please carefully read the content of the revised Privacy Policy. <strong>If you continue to use our services, it indicates that you agree to our processing of your personal information in accordance with the updated Privacy Policy.</strong>
    </p>

    <h2>8. Protection of Minors</h2>
    <p>
        We encourage parents or guardians to guide minors under the age of eighteen in using our services. We suggest minors encourage their parents or guardians to read this Privacy Policy and recommend that minors seek the consent and guidance of their parents or guardians before submitting personal information.
    </p>

</main>

{% endblock %}

templates/LibroLink/register.html
{% extends 'LibroLink/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
<h1>Register for 'LibroLink'</h1>
{% if registered %}
<strong>Thank you for registering!</strong>
<a href="{% url 'LibroLink:index' %}">Return to the homepage</a><br />
{% else %}
<strong>Register here!</strong><br />
<form id="user_form" method="post" action="{% url 'LibroLink:register' %}" enctype="multipart/form-data">
    {% csrf_token %}

    {{ user_form.as_p }}
    {{ profile_form.as_p }}

    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}
{% endblock %}

templates/LibroLink/search_results.html
{% extends 'LibroLink/base.html' %}

{% block title_block %}
Search Results
{% endblock %}

{% block body_block %}
<div class="container">
    <h1>Search Results</h1>
    {% if books %}
        <ul>
            {% for book in books %}
                <li>
                    <strong>{{ book.title }}</strong> by {{ book.author }} (ISBN: {{ book.isbn }})
                    <p>{{ book.publisher }}</p>
                    <!-- Other details you want to display -->
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No books found.</p>
    {% endif %}
</div>
{% endblock %}

templates/LibroLink/updateProfile.html
{% extends 'LibroLink/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Update Profile
{% endblock %}

{% block body_block %}
        <form id= "user_form" method="post" action="{% url 'register' %}"
    enctype="multipart/form-data">

        {% csrf_token %}

        {{ user_form.as_p }}
        {{ profile_form.as_p }}

        <div class="button-holder">
            <input type="submit" name="submit" value="Update" class="button" />
        </div>
    </form>
{% endblock %}

templates/LibroLink/user_not_found.html
{% extends 'LibroLink/base.html' %}
{% load static %}

{% block title_block %}
    Friends
{% endblock %} 

{% block body_block %} 
    <h1>User Not Found</h1>
    <p>The user with username "{{ username }}" does not exist.</p>
{% endblock %} 